### ISSUE TITLE
Run on Mac OSx (chip Apple M1 Pro)

### ISSUE THREAD

**Issue by EMbeDS-education** [BPM-Research-Group/Ebi#1]
Hello,

I would like to install and use the tool on a Mac OSx (chip Apple M1 Pro). Do you have any suggestion?
I tried following the install instructions in the readme, but I got stuck at 'Add an SSH key to your RWTH Gitlab account'.

**Comment by sleemans** [comment]
Hihi,

We've removed these outdated steps from the readme file. You can clone the repository as usual, and run Ebi using "cargo run".

**Comment by brucelit** [comment]
Hi, 

to run Ebi project, you can clone it first to your Macbook. Then in your terminal, run Ebi using "cargo run". 
For example, the command "Ebi analyse all-traces" should be "cargo run analyse all-traces" in MacOS.
