### ISSUE TITLE
Output the runtime of the core algorithm

### ISSUE THREAD

**Issue by EduardoGoulart1** [BPM-Research-Group/Ebi#6]
It would be great for experiments if one could measure the runtime of the core methods, discounting the time to load the inputs.

I guess this could be easily achieved by starting a timer [right before executing](https://github.com/BPM-Research-Group/Ebi/blob/3e99bf5de76b30247fcde20ff3a949f68d00ac80/src/ebi_framework/ebi_command.rs#L225) and then logging it

**Comment by sleemans** [comment]
Added, thanks for the suggestion!
